name: Build and Deploy Angular App to IIS

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch

jobs:
  CICD:
    runs-on: windows-latest  # or use windows-latest if you want to use Windows Runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Set the Node.js version you want to use

    - name: Install Dependencies
      run: npm install  # Install Angular dependencies

    - name: Build Angular App
      run: npm run build --prod  # Build the Angular app for production

    - name: Archive Build Files
      run: |
        mkdir -p build-artifacts
        cp -r dist/* build-artifacts/  # Copy build output to a new folder

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: angular-build
        path: build-artifacts/  # Upload the build artifacts to GitHub
        
    - name: List uploaded artifacts
      run: |
        echo "Listing artifacts uploaded in this job:"
        ls -R build-artifacts/    

    # Download the build artifact
    - name: Download Angular Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: angular-build
        path: build-artifacts/angular-build

    # Step 6: Deploy to IIS via FTP
    - name: Deploy via FTP to IIS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3  # Use the correct latest version of the action
      with:
        server: '108.181.161.179'  # Your FTP server address
        username: ${{ secrets.FTP_USERNAME }}  # Your FTP username
        password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password
        port: 21  # Default FTP port
        local-dir: ./build-artifacts/my-angular-app/  # Path to the downloaded build files
        server-dir: C:/IRIS5/site.cicd/  # Target folder on the IIS server
          
          